services:

  website1:
    build:
      context: ./website1
    container_name: shopsphere
    expose:
      - "80"
    restart: unless-stopped

  website2:
    build:
      context: ./website2
    container_name: fooddash
    expose:
      - "80"
    restart: unless-stopped

  website3:
    build:
      context: ./website3
    container_name: travelgo
    expose:
      - "80"
    restart: unless-stopped

  website4:
    build:
      context: ./website4
    container_name: fintrack
    expose:
      - "80"
    restart: unless-stopped

  router:
    build:
      context: ./router
    container_name: website-router
    environment:
      - ACTIVE_SITE=1
    expose:
      - "5000"
    depends_on:
      - website1
      - website2
      - website3
      - website4
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    container_name: nginx-router
    ports:
      - "80:80"
    depends_on:
      - router
    restart: unless-stopped
